// Generated by CoffeeScript 1.10.0

/* 
  how about some coffee with your fromage? :D
 */

(function() {
  var Fromage;

  Fromage = (function() {
    function Fromage() {}

    Fromage.prototype.examine = function() {
      return console.log('whoa this js stinks!');
    };

    Fromage.prototype.init = function() {
      console.log('fromage is coming.');
      return this.examine();
    };

    return Fromage;

  })();

}).call(this);
